// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using DemoCamera;
//
//    var customResponseModel = CustomResponseModel.FromJson(jsonString);

namespace DemoCamera3.Model
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class CustomResponseModel
    {
        [JsonProperty("isIdentical")]
        public bool IsIdentical { get; set; }

        [JsonProperty("confidence")]
        public double Confidence { get; set; }
    }

    public partial class CustomResponseModel
    {
        public static CustomResponseModel FromJson(string json) => JsonConvert.DeserializeObject<CustomResponseModel>(json, DemoCamera3.Model.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this CustomResponseModel self) => JsonConvert.SerializeObject(self, DemoCamera3.Model.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
