// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using DemoCamera;
//
//    var faceCompareModel = FaceCompareModel.FromJson(jsonString);


namespace DemoCamera2.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class FaceCompareModel
    {
        [JsonProperty("faceId1")]
        public string FaceId1 { get; set; }

        [JsonProperty("faceId2")]
        public string FaceId2 { get; set; }
    }

    public partial class FaceCompareModel
    {
        public static FaceCompareModel FromJson(string json) => JsonConvert.DeserializeObject<FaceCompareModel>(json, DemoCamera2.Models.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this FaceCompareModel self) => JsonConvert.SerializeObject(self, DemoCamera2.Models.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}